# Ergo Kotlin client CI workflow
---
name: "Ergo client CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build & Test ergo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Declare Version Variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Build & Test
        run: ./gradlew build